---
# path to your media folder.
# please use slashes instead of backslashes even on windows.
# no trailing slashes!
media_path: F:/Tv Shows

# preferred locale for subtitles.
subs_locale: it

# the player you wish to use.
player: mpc.sh